[package]
name = "dmesh-doca"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
description = "Small DOCA initialization wrapper for linkerd2-proxy"

[features]
default = ["own-datapath"]
# Compile the bundled C datapath and DOCA owner.
own-datapath = []

[dependencies]
tracing = { workspace = true }
async-trait = "0.1"
linkerd-io = { path = "../io" }
parking_lot = "0.12"
prometheus-client = { workspace = true }
tokio = { version = "1", features = ["macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1", features = ["net", "rt", "sync", "time", "macros", "io-util"] }

[build-dependencies]
cc = "1"
pkg-config = "0.3"
